### PR TITLE
Better configs management

### PR DESCRIPTION
**Pull request by U-L-M-S**

### CODE REVIEW

**Comment by Youngermaster** [comment]
@U-L-M-S Thank you for your words in the `.txt` file, literally my reaction was like [Di Maria's reaction](https://www.youtube.com/watch?v=CEMqS9KiSMo&ab_channel=ANDRESPORTS). I'm glad this repo has been of help to you and even caught the attention of your co-workers! If you need more you can check other repos like [Arch dotfiles](https://github.com/Youngermaster/Arch-dotfiles) if you or your coworkers need more inspiration or files. Or if you have more suggestions feel free to make more Pull Requests.

After reading your message, I took a peek at your profile's README and noticed you're working at Collax. The role of `Ausbildung Fachinformatiker Anwendungsentwicklung` caught my eye and sounds truly intriguing. If ever the opportunity arises, I'd genuinely be interested in exploring possibilities at Collax. I'm always up for a challenge, and I'm committed to picking up the German language swiftly if required. Regardless, **keep rocking that setup and best wishes to you and your team!**

**Comment by U-L-M-S** [comment]
@Youngermaster Thank you :) Actually... I started my charier in the Economy area... but I didn't feel so great there so 2 Years ago I start studying Cyber-Security but because of some family problems I decided to start a Ausbildung ( pastry training as a Software Developer). Thank you sooo much for your answer! I was **not** expecting it :smile: 

I wish you all the best, broh :smile:

**Comment by Youngermaster** [comment]
@U-L-M-S, It's inspiring to hear about your journey from the Economy area to Cyber-Security and now into software development through the Ausbildung. Life often takes us through unexpected twists and turns, but it's evident that you have a passion and drive that helps you navigate these changes. It's a testament to your resilience and adaptability. 💪🏻

Your kind words genuinely made my day. I always appreciate hearing from people who find value in my work. Remember, every experience you've had contributes to your unique perspective, which I'm sure will be a valuable asset in the tech world.

Take care, and if ever you want to chat about software, tech, or anything in between, don't hesitate to reach out. All the best on your software development journey, and here's to many more successes and cool setups in the future! 😄

**Comment by U-L-M-S** [comment]
Thank you, @Youngermaster  :smile: In case you want to keep in touch with me here is my telegram: https://t.me/T0rv4

I would love to give you my email. But for security reasons I will not post it here.

**Pull request merged**
